# Site settings
title: Shubham Kumar Singh
twitter_username: Shubham02468
name: Shubham Kumar Singh

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:

 - title: LinkedIn
   url: https://www.linkedin.com/in/shubhamkumarsingh/
 - title: Facebook
   url: https://www.facebook.com/shubhamkumar2jan/
 - title: GitHub
   url: https://github.com/shubhamsingh
 - title: HackerRank
   url: https://www.hackerrank.com/SHUBHAM_SINGH002  
 - title: CodeChef
   url: https://www.codechef.com/users/shubham002
 - title: LeetCode
   url: https://leetcode.com/shubhamsingh002/


#Any buzzword skills you want to include
skills:
 - Cloud Computing
 - Network Security
 - Scala
 - Microservices
 - API design
 - C
 - Python
 - SQL
 - REST
 - Technical Architecture
 - Machine learning
 - Deep Learning
 - Computer Vision

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Member of Technical Staff
   start: 2019
   end: Ongoing
   employer: Nutanix Technology India Pvt Limited
   description: Nutanix, Inc. is a cloud computing company. 

#Education is required
education:
 - level: Master of Technology (M.Tech.)
   date: 2017
   subject: Computer Science and Engineering
   school: IIT Gandhinagar
   
 - level: Bachelor of Technology (B.Tech.)
   date: 2012
   subject: Computer Science and Engineering
   school: Jaypee University of Information Technology, Solan
 
 - level: Senior Secondary level 10+2
   date: 2011
   school: Bal Bharti School, Allahabad
   
 - level: Secondary level 10
   date: 2009
   subject: Computer Science and Engineering
   school: Swami Vivakananda Vidya Ashram, Allahabad


#This section is optional (as is the image link below)
# coursera:
#    profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#    courses:
#     - title: Functional Programming Principles in Scala
#       link: https://www.coursera.org/course/progfun
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#       date: September 16, 2013
#     - title: Algorithms Design and Analysis, Part 1
#       link: https://www.coursera.org/specializations/algorithms
#       optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#       date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - shubhamsingh/shubhamsingh.github.io
 - shubhamsingh/Single-Shot-Object-Detector
 - shubhamsingh/Restaurant-Recommender-System
 - shubhamsingh/Machine_Learning
 - shubhamsingh/3D-Computer-Vision
 - shubhamsingh/MarketingAnalytics
 - shubhamsingh/Python
 - shubhamsingh/C_Project
 - shubhamsingh/turocprograms

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl: https://stackoverflow.com/users/258813/rhinds
#    flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  Software developer with 2+ years industrial experience participating in the complete product development life cycle of successfully launched applications. I am looking an opportunities to work in challenging environment towards designing futuristic products/services and helps me acknowledge my potential as on. <br/><br/>
  

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>M.Tech Thesis: Person Re-Identification Problem, Prof. Shanmuganathan Raman. (Jan 2018-June 2019)</strong>: Person Re-Identification Problem is defined as matching people across disjoint camera views in the multi-camera system. It is useful in public security application such as intelligent camera surveillance system.
           We propose Deep Parallel Feature Consensus Network (DeepPFCN), a novel network architecture that learns multi-scale person appearance features using convolutional neural networks and factories the visual appearance of a person into latent discriminative factors at multiple semantic levels and after that consensus is achieved.
           Published a paper in NCVPRIPG 2019 titled "DeepPFCN: Deep Parallel Feature Consensus Network for Person Re-Identification", a novel network architecture performed better on benchmark datasets. <br/><br/>
   <strong>Developed Advance Web-based surveillance system for Ahmedabad Rath Yatra. [Team of 2] (Jun 2018-May 2019)</strong>: Completed the combined project of IIT Gandhinagar and Raksha Shakti University Ahmedabad under the guidance of Prof. Shanmuganathan Raman and Prof. Krishna Prasad from IIT Gandhinagar.
           Developed a prototype on web-based advanced surveillance system for crowd monitoring and Rath tracking using HTML, JavaScript, Google MAP API, Embedded camera in GMAP locations. <br/><br/>
   <strong>Text to Image Synthesis using StackGAN with Domain Adaptation. [Team of 3] (Jan-Apr 2018)</strong> Implemented Deep Learning-based Approach GAN, StackGan, CNN for generating different domain images (Flower) with the given text and combined (Bird+Flower) data sets and obtain slightly better domain adaptation results as able to create flower images. <br/><br/>
   <strong>B.Tech Final Year Project: Efficient Energy Management in Data Centers, Prof. Amit Singh. (Jul 2015-Jun 2016)</strong>: Data centers hosting cloud computing applications consume vast amounts of energy, contributing to high operational costs and carbon footprints.
           Implemented dynamic voltage and frequency scaling, load balancing and dynamic shutdown on the GreenCloud simulator and found that we can potentially reduce the energy consumption of servers by around 50%. <br/><br/>
   <strong>Image Enhancing and Noise Removal using GUI in Matlab, Prof. Pragya Gupta and Tapan Jain. (Jan-Jul 2014)</strong>: Implemented Graphical User Interface Photo editor in MatLab using Image Enhancing technique such as Logarithm Operation, Exponential Raise to Power Operation, Histogram Equalization, Negative Edge Detection and Noise Removal technique such as Gaussian Noise, Low pass Filter, Weiner Filter.<br/><br/>
   
